# Generated by Django 5.2.7 on 2025-10-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(help_text='Unique aircraft registration number (e.g., TC-NRT)', max_length=20, unique=True)),
                ('model', models.CharField(help_text='Aircraft model (e.g., Airbus A320, Boeing 737)', max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum passenger capacity')),
                ('production_year', models.PositiveIntegerField(help_text='Year the aircraft was manufactured')),
                ('status', models.BooleanField(default=True, help_text='Aircraft operational status (True=Active, False=Inactive)')),
            ],
            options={
                'verbose_name': 'Airplane',
                'verbose_name_plural': 'Airplanes',
                'ordering': ['-production_year', 'tail_number'],
            },
        ),
    ]
