# Generated by Django 5.2.7 on 2025-10-23 07:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(help_text='Full name of the passenger', max_length=200)),
                ('passenger_email', models.EmailField(help_text="Passenger's email address for confirmation", max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('reservation_code', models.CharField(blank=True, editable=False, help_text='Unique reservation code (automatically generated)', max_length=10, unique=True)),
                ('status', models.BooleanField(default=True, help_text='Reservation status (True=Active, False=Cancelled)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the reservation was created')),
                ('flight', models.ForeignKey(help_text='The flight this reservation is for', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flight', '-created_at'], name='reservation_flight__de020e_idx')],
            },
        ),
    ]
