# Generated by Django 5.2.7 on 2025-10-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Unique flight identifier (e.g., TK123, BA456)', max_length=20, unique=True)),
                ('departure', models.CharField(help_text='Departure airport or location (e.g., Heathrow Airport)', max_length=200)),
                ('destination', models.CharField(help_text='Destination airport or location (e.g., Istanbul Airport)', max_length=200)),
                ('departure_time', models.DateTimeField(help_text='Date and time when the flight departs')),
                ('arrival_time', models.DateTimeField(help_text='Date and time when the flight arrives')),
                ('airplane', models.ForeignKey(help_text='The airplane assigned to this flight', on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airplanes.airplane')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('arrival_time__gt', models.F('departure_time'))), name='arrival_after_departure')],
            },
        ),
    ]
